exporter/clickhouselogsexporter/migrations/000002_add_minmax_idx.down.sql, exporter/clickhouselogsexporter/migrations/000002_add_minmax_idx.up.sql
Id was a secondary column in the ordery by clause (primary key), it resulted in slower queries when the timerange is large for certain operations.
after adding a minmax index, which is very lightweight the queries for pagination using id and finding a specific id is reduced to  sub `50`milliseconds from about `1` s
=> minmax index added to id for faster pagination

.github/workflows/lint-and-test.yaml, .golangci.yml, cmd/signozcollector/Dockerfile, go.mod
#26 only updated the version in Dockerfile. This bumps the version in workflows and makes it consistent across manyplaces.
=> Update workflows to use correct version and be consistent

exporter/clickhousemetricsexporter/exporter_test.go, exporter/clickhousemetricsexporter/factory_test.go
They should be enabled when there is a proper fix for https://github.com/SigNoz/signoz-otel-collector/issues/65.
On a side note, I would like to ask if it's generally recommended/practised approach that the connection should be established in the new object instantiation with `NewXX` or when the `Start` is actually called on the exporter; even outside this project, is it common?
=> Temporarily skip some metrics exporter tests

exporter/clickhouselogsexporter/exporter.go, exporter/clickhouselogsexporter/factory.go
Fixes https://github.com/SigNoz/signoz-otel-collector/issues/76
similar to https://github.com/SigNoz/signoz-otel-collector/pull/78 but this is for logs
=> Add DB latency metric instrumentation for clickhouselogsexporter

constants/os_utils.go, opamp/server_client.go
This PR introduces an additional non-identity attribute `capabilities.lb` in opamp collector. 
The value can be 1 or 0 where 1 indicates - the collector is capable of supporting lb exporter config and 0 otherwise. 
When the support for lb exporter capability is enabled, the opamp server can use the collector as LB. but need not always set it so. 
By default, all collectors will support LB config. The SUPPORT_LB_EXPORTER_CONFIG env var can be used to disable the support (by setting this env var to 0). 
Typically at design time, the env var SUPPORT_LB_EXPORTER_CONFIG can be used to define LB capable collectors ( could be 0 to n) or (non-LB collectors). This would allow options to support multiple configurations depending on customer environment.
=> feat: added flag to enable lb exporter collectors

exporter/clickhousemetricsexporter/exporter.go
Exit without panic if the ClickHouse connection is failed to establish. This usually happens when the URL is misconfigured or similar network-related issues. Part of https://github.com/SigNoz/signoz/issues/1639
=> exit when ClickHouse client creation fails

.gitignore, opamp/server_client_test.go, opamp/testdata/coll-config-path-changed.yaml, opamp/testdata/coll-config-path.yaml, signozcol/collector_test.go, signozcol/testdata/config.yaml, signozcol/testdata/invalid_config.yaml
This change removes the usage of `clickhouse{traces,metricswrite}` exporters in tests. Otherwise, tests fail in when the connection is not available. There is nothing about the ClickHouse in these tests, so there is no point in starting up a container for DB during the CI run.
=> fix: tests do not require db

exporter/clickhousetracesexporter/clickhouse_exporter.go
Removed events tag as span attributes because events is of array type and it's not supported currently.
Removed startTime tag as span attributes because user can filter via timestamp and startTime tag is not required
=> fix: remove events and startTime span attributes

cmd/signozcollector/Dockerfile
Fixes #155
Successfully tested [the built image](https://hub.docker.com/layers/coolboi567/signoz-otel-collector/test/images/sha256-ad2a08a487365c19255692c826cdb17cc02f70b2b8fac4eea59daea28e2695d4?context=explore) in ARM64 machine.
=> fix(Dockerfile): 🐛 remove overriding of TARGETOS and TARGETARCH

exporter/clickhouselogsexporter/migrations/000007_default_indexes.down.sql, exporter/clickhouselogsexporter/migrations/000007_default_indexes.up.sql
Fixes https://github.com/SigNoz/signoz/issues/2594
No point in addding index for trace_id, span_id as they are not set and they are always unique
=> feat: add default indices for top level keys

exporter/clickhousetracesexporter/writer.go
fix: https://github.com/SigNoz/engineering-pod/issues/1028
=> chore: use map to reduce writes to clickhouse tag tables

exporter/clickhouselogsexporter/config.go, exporter/clickhouselogsexporter/config_test.go, exporter/clickhouselogsexporter/factory.go
Have kept the same logic as we need to keep the queueSize configurable.
fixes #181
=> fix: use default num consumers

exporter/clickhouselogsexporter/migrations/000005_attribute_rename.up.sql
=> fix: migration reapply issue fixed for logs

exporter/clickhouselogsexporter/exporter.go, migrationmanager/migrators/logs/migrations/000008_add_bool.down.sql, migrationmanager/migrators/logs/migrations/000008_add_bool.up.sql
Fixes #209 
* Previously we directly stored bool values as as string.
* When we added tag attributes support that time this bug got introduct when the attribute wasn't stored in with log line.
* Added changes so that the bool values are stored.
Suggestes and querying work as expected.
=> fix: ingest bool attrs

exporter/clickhouselogsexporter/exporter.go
The defer function was not executed properly in the previous implementation, because of which connections were kept on hold.
Now even if I use maxOpenConnection = numConsumers - 1, once it fails to acquire connection it will retry and it is eventually successful.
Fixes https://github.com/SigNoz/signoz-otel-collector/issues/222
=> fix: proper defer statement for log exporter

exporter/clickhousemetricsexporter/clickhouse.go, exporter/clickhousemetricsexporter/exporter.go, exporter/clickhousemetricsexporter/usage.go
- We no longer use JSON Object type (which will be removed soon). There is no need to set `allow_experimental_object_type`
- The write table should be distributed table
- Do not throw an error for non-actionable invalid data errors. The ideal thing to do is to surface these issues in the metrics explorer or somewhere but that's separate work.
- Update incorrect description
=> Add warning message for invalid data and update TS write table

opamp/client.go, opamp/server_client.go
Right now, if ensureRunning happens to catch a stopped collector svc while a config reload is in progress, it triggers process level shutdown.
Fixes https://github.com/SigNoz/signoz/issues/4181
=> fix: opamp client: ignore non-running collector in ensureRunning when reloading collector config

exporter/clickhousemetricsexporter/clickhouse.go, exporter/clickhousemetricsexporter/config.go, exporter/clickhousemetricsexporter/config_test.go, exporter/clickhousemetricsexporter/exporter.go, exporter/clickhousemetricsexporter/factory.go, migrationmanager/migrators/metrics/migrations/000003_ts_v4.down.sql, migrationmanager/migrators/metrics/migrations/000003_ts_v4.up.sql, receiver/signozkafkareceiver/kafka_receiver.go
We maintain two tables in the metrics database
1. samples
2. time_series
The `samples` table contains the metric value and timestamp it was collected at. The `time_series` table contains the metric_name + tags (referred to as timeseries) and the first instance of the timestamp at which the new series was created.
One way to model the schema is to have a single table with all the data.
- value
- timestamp
- tags (either map or pairwise array or json encoded string)
The speed of the query is dependent on the amount of data it has to read. Reading labels from map/array/json encoded string is slow since it has to read the full labels and unpack it (map is just an array underneath). So the more rows you have the slower the query will be. One important characteristic of the timeseries data is …
=> Write to new v4 table with nearest hour unix precision

exporter/clickhousemetricsexporter/exporter.go, exporter/clickhousemetricsexporter/helper.go, exporter/clickhousemetricsexporter/helper_test.go
Certain OTEL SDKs are sending empty data points. This isn't an error we can act on so skipping with warning.
=> Log warn for empty batch instead of error

receiver/signozkafkareceiver/config.go, receiver/signozkafkareceiver/config_test.go, receiver/signozkafkareceiver/kafka_receiver.go, receiver/signozkafkareceiver/testdata/config.yaml
This PR exposes some of the sarama library's fields like max processing time, max channel size, etc
This would enable us to override these values when required
=> signozkafkareceiver: expose sarama consumer config

migrationmanager/migrators/traces/migrations/000025_add_time_column_ttl_top_level.down.sql, migrationmanager/migrators/traces/migrations/000025_add_time_column_ttl_top_level.up.sql
Fixes https://github.com/SigNoz/signoz/issues/4265
Fixes https://github.com/SigNoz/signoz-otel-collector/issues/252
Currently, the `top_level_operations` doesn't have any table. This leads to a couple of issues
- The (test) services are kept in db forever.
- Incorrect top-level operations are kept forever without any cleanup. Assume some operation was identified as top-level operation due to incorrect/broken instrumentation.
=> Add TTL to top_level_operations table

processor/signozspanmetricsprocessor/config.go, processor/signozspanmetricsprocessor/factory.go, processor/signozspanmetricsprocessor/processor.go
Follow up https://github.com/SigNoz/signoz-otel-collector/pull/279#issuecomment-1934619152. This is more accurate (i.e. as close to latency from traces) and faster. 
- Not enabled by default
- The default max size is 160, and it supports high-resolution tail latency distribution covering 1ms-100s (we need to bump the size if we want more); to achieve the same in explicit bucket histogram we need to define 160 buckets. Which makes the queries slower and samples by 10x of the current samples. 
The query would change
<details><summary>From</summary>
```sql
SELECT
service_name,
ts,
histogramQuantile(arrayMap(x -> toFloat64(x), groupArray(le)), groupArray(value), 0.99) AS value
FROM
(
SELECT
service_name,
le,
ts,
sum(rate_value) AS value
FROM
(
SELECT
service_name,
le,
ts,
If((value - …
```
=> Add experimental support for APM latency with Exp Histogram

processor/signozspanmetricsprocessor/config.go, processor/signozspanmetricsprocessor/config_test.go, processor/signozspanmetricsprocessor/factory.go, processor/signozspanmetricsprocessor/processor.go, processor/signozspanmetricsprocessor/processor_test.go, processor/signozspanmetricsprocessor/testdata/config-full.yaml
Part of https://github.com/SigNoz/signoz/issues/4654
Set an upper limit of 248 services and 2048 unique operations for each service. The limits are configurable.
=> Introduce max services and max ops per service limits

exporter/clickhousetracesexporter/clickhouse_exporter.go, exporter/clickhousetracesexporter/clickhouse_factory.go, exporter/clickhousetracesexporter/writer.go
The traces table latency goes as high as minutes because it doesn't respect the parent context cancellation. The other two exporters do and will have a maximum of `timeout` latency. Without this change, the timeout setting is useless https://github.com/SigNoz/signoz-otel-collector/blob/59f483969686b9f9c5a214696d2ca87eed3f45f6/exporter/clickhousetracesexporter/factory.go#L32-L34
=> Use parent context for write* operations

components/components.go, go.mod, go.sum
Adds the Datadog APM receiver for traces.
Note that I included the same version as the other contrib components were (v0.88.0) which is 5 months behind the latest version (v0.96.0)
Jochen Mehlhorn <jochen.mehlhorn@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH
[Provider Information](https://github.com/Daimler/daimler-foss/blob/master/PROVIDER_INFORMATION.md)
=> Adds Datadog APM receiver

.gitignore, exporter/signozkafkaexporter/kafka_exporter.go, exporter/signozkafkaexporter/utils.go
- Return a default topic name when `signoz_tenant_id` is missing in the metadata
- Change name of the function `getKafkaTopicPrefixFromClientMetadata` to reflect what it is actually doing.
=> (feat) return a default topic when tenant_id is not present

receiver/httplogreceiver/httplogreceiver.go
=> fix: httplogreceiver use logs obsreport instead of metrics

exporter/clickhouselogsexporter/exporter.go, migrationmanager/migrators/logs/migrations/000010_add_instrumentation_scope.down.sql, migrationmanager/migrators/logs/migrations/000010_add_instrumentation_scope.up.sql
Otel collector changes for  https://github.com/SigNoz/signoz/issues/2705
=> feat: add instrumentation scope support

exporter/clickhouselogsexporter/exporter.go, migrationmanager/migrators/logs/migrations/000012_rename_instrumentation_scope.down.sql, migrationmanager/migrators/logs/migrations/000012_rename_instrumentation_scope.up.sql
part of https://github.com/SigNoz/signoz/issues/2705
Renames `instrumentation_scope, instrumentation_scope_version, instrumentation_scope_attributes_string_{key/val}`
to
`scope_name , scope_version , scope_string_{key,value}`
=> feat: rename instrumentation_scope to scope

exporter/clickhouselogsexporter/exporter.go, migrationmanager/migrators/logs/migrations/000013_rename_instrumentation_scope.down.sql, migrationmanager/migrators/logs/migrations/000013_rename_instrumentation_scope.up.sql
No migration is required as 
`tagType Enum8('tag' = 1, 'resource' = 2, 'instrumentation_scope' = 3) CODEC(ZSTD(1))`
is changed to 
`tagType Enum8('tag' = 1, 'resource' = 2, 'scope' = 3) CODEC(ZSTD(1))`
=> fix: tagAttributes table fix for instrumentation scope

migrationmanager/migrators/metrics/migrations/000008_samples_agg_tables.down.sql, migrationmanager/migrators/metrics/migrations/000008_samples_agg_tables.up.sql
The supported temporal aggregation in metrics are
- latest
- min
- max
- avg
- sum
- count
- count distinct
This change adds a pre-aggregated table with
- last (to support the latest)
- min
- max
- sum
- count
The `avg` will be calculated using `sum/count`. We don't support count distinct because it is rarely used and doesn't need pre-aggregation wherever it is used. 
Please see https://www.notion.so/signoz/Metrics-samples-aggregation-tables-71db1d3ac3724f5ba693e0e99eb352ce for additional detail and how the queries would be written on these tables.
=> Add pre-aggregation tables with 5m and 30m resolution for samples v4

migrationmanager/migrators/logs/migrations/000014_new_schema.up.sql
We don't want to use `enableReplication` = true just for these tables, so hardcoding them to use replicaed.
=> feat: hardcode replicated for the new logs tables

exporter/clickhouselogsexporter/exporter.go
The err would be nil at this point in code so the returned error would be `StatementSend:%!w(<nil>)` which breaks the logic used in removing log entries based ttl.
=> Use correct error variable for wrapped error

exporter/clickhouselogsexporter/config.go, exporter/clickhouselogsexporter/config_test.go, exporter/clickhouselogsexporter/exporter.go, exporter/clickhouselogsexporter/testdata/config.yaml
Fixes https://github.com/SigNoz/signoz-otel-collector/issues/372
* with the new schema we stored in64 tag attributes as float64 which broke the suggestions api for old users with int64 keys.
* this PR fixes this issue and also adds a new config option.
=> fix: write int64 tag attributes for old schema

exporter/clickhouselogsexporter/exporter.go
NewRandomWithTime fixes the current issues that we have with id's
* Ids will now respect the timestamp of the log line regardless of when it is ingested.
* During collision of timestamp the randomness of 16 bits will make sure that there is no collision between logs of same timestamp. ( probability is one in billion)
=> feat: correct id generation for log timestamp

cmd/signozschemamigrator/schema_migrator/column_operations.go, cmd/signozschemamigrator/schema_migrator/column_operations_test.go
Covers the column manipulations mentioned in https://clickhouse.com/docs/en/sql-reference/statements/alter/column to be written declaratively in migration.
1. [ADD COLUMN](https://clickhouse.com/docs/en/sql-reference/statements/alter/column#add-column) - AlterTableAddColumn
2. [DROP COLUMN](https://clickhouse.com/docs/en/sql-reference/statements/alter/column#drop-column) - AlterTableDropColumn
3. [RENAME COLUMN](https://clickhouse.com/docs/en/sql-reference/statements/alter/column#rename-column) - this operation is not supported. Renaming the column is a two-step process. See [here](https://www.notion.so/signoz/CH-Mutations-aware-schema-migrations-80a19988fd5a4558afa1e5d5de5cc57e?pvs=4#a63ad5338acb4388a66c0b3293ffdac9)
4. [CLEAR COLUMN](https://clickhouse.com/docs/en/sql-reference/statement …
=> Add ALTER COLUMN operations

cmd/signozschemamigrator/schema_migrator/index_operations.go, cmd/signozschemamigrator/schema_migrator/index_operations_test.go
Covers the index manipulations mentioned in https://clickhouse.com/docs/en/sql-reference/statements/alter/skipping-index to be written declaratively in migration.
- [ADD INDEX](https://clickhouse.com/docs/en/sql-reference/statements/alter/skipping-index#add-index) - AlterTableAddIndex
- [DROP INDEX](https://clickhouse.com/docs/en/sql-reference/statements/alter/skipping-index#drop-index) - AlterTableDropIndex
- [MATERIALIZE INDEX](https://clickhouse.com/docs/en/sql-reference/statements/alter/skipping-index#materialize-index) - AlterTableMaterializeIndex
- [CLEAR INDEX](https://clickhouse.com/docs/en/sql-reference/statements/alter/skipping-index#clear-index) - AlterTableClearIndex
=> Add INDEX operations

cmd/signozschemamigrator/schema_migrator/table.go, cmd/signozschemamigrator/schema_migrator/table_operations.go, cmd/signozschemamigrator/schema_migrator/table_operations_test.go, cmd/signozschemamigrator/schema_migrator/table_test.go
Support most of the operations mentioned in create table https://clickhouse.com/docs/en/sql-reference/statements/create/table
The `TableEngine` interface defines the funcs each table engine needs to implement. The following are supported table engines 
1. MergeTree
2. ReplacingMergeTree
3. AggregatingMergeTree
4. SummingMergeTree
and special distributed
5. Distributed
The operations on the table
1. CreateTableOperation
2. DropTableOperation
3. CreateMaterializedViewOperation
There are some operations we don't support not because they can't be supported but they aren't needed right now. They can be implemented where there is a need.
=> Add TABLE operations

migrationmanager/migrators/logs/migrations/000015_resource_label_index.down.sql, migrationmanager/migrators/logs/migrations/000015_resource_label_index.up.sql
Since we decided to go with case-sensitive for attributes and resources, the old index won't be triggered. So we are adding this.
=> feat: add labels index in resource_v2 table

cmd/signozschemamigrator/schema_migrator/manager.go, cmd/signozschemamigrator/schema_migrator/squashed_logs_migrations.go, cmd/signozschemamigrator/schema_migrator/squashed_metrics_migrations.go, cmd/signozschemamigrator/schema_migrator/squashed_traces_migrations.go
The goal is to get rid of all `.sql` based operations and files. This changes creates a "squashed" migration containing the current snapshot of the schema
=> Add squashed migrations

exporter/clickhousemetricsexporter/exporter.go
This change increases maxBatchByteSize to reduce the number of writes for big batches.
=> Increase split size for metric writer

cmd/signozschemamigrator/main.go, cmd/signozschemamigrator/schema_migrator/manager.go
The connection string often includes critical information like username and password, which should be retained for future connection attempts. This modification ensures that the options specified in the --dsn argument are preserved and applied when establishing connections to other shards.
=> Use the options from dsn for new connections

receiver/signozkafkareceiver/kafka_receiver.go
Related to opentelemetry-collector/issues/9824. We do not want to report a Fatal error on context cancel because the consume stop involves context cancelling and ending the loop.
=> Do not report fatal on context cancel

usage/usage.go
flush usage metrics after stopping the usage reader
opened, this PR as I pushed dummy commits to the last PR.
=> fix: flush usage metrics after stopping the usage reader

exporter/clickhouselogsexporter/exporter.go, utils/fingerprint/fingerprint.go, utils/fingerprint/fingerprint_test.go, utils/fingerprint/hash.go
Since I am using this package in traces, creating an individual PR to move this to utils so that it can be common.
=> fix: move fingerpint package to utils for it to be used by others

cmd/signozschemamigrator/main.go, cmd/signozschemamigrator/schema_migrator/manager.go
add development flag for schemamigrator which will return empty values for HostAddrs.
```
go run cmd/signozschemamigrator/main.go --dsn http://localhost:9000 --replication=true --dev=true sync
```
=> fix: add development flag for schemamigrator

go.sum, receiver/signozkafkareceiver/kafka_receiver.go, receiver/signozkafkareceiver/kafka_receiver_test.go
- Apply backpressure on kafka on memorylimiter error. Pause the consumption and retry in place. This relives kafka of continuous rebalancing and gives a predictable memory workload for the collector
=> feat(kafka): apply backpressure

cmd/signozschemamigrator/schema_migrator/table_operations.go, cmd/signozschemamigrator/schema_migrator/table_operations_test.go
=> feat: support for modify query mat col in migrations

exporter/clickhousetracesexporter/clickhouse_exporter.go, exporter/clickhousetracesexporter/clickhouse_factory.go, exporter/clickhousetracesexporter/config.go, exporter/clickhousetracesexporter/options.go
Currently `clickhousetraces` uses hardcoded cluster name `cluster` which doesn't allow to use different cluster.
This PR implements it as configuration option so any cluster can be specified.
=> clickhousetraces: Support specifying cluster

exporter/clickhouselogsexporter/exporter.go
Since we already store resource attributes as strings the query sent by user is correct but and the query builder also builds the correct query but since the label value doesn't contains `'` it fails. This pr fixes that issue.
The same goes for an array of strings.
TLDR :- 
resources {
"arr": ["a", "b", "c"],
"num" : 123 
}
will be stored as
`{"arr":"[\"a\",\"b\",\"c\"]","num":"123"}`
Fix for https://github.com/SigNoz/signoz/issues/6307
=> fix: use string values for resource labels

cmd/signozschemamigrator/schema_migrator/table_operations.go, cmd/signozschemamigrator/schema_migrator/table_operations_test.go
Add support for settings in drop table
FOR https://github.com/SigNoz/signoz/issues/5713
=> fix: add settings to drop table

cmd/signozschemamigrator/schema_migrator/traces_migrations.go
don't drop actual duration sort table
=> fix: don't drop actual duration sort table

exporter/clickhouselogsexporter/exporter.go, exporter/clickhousetracesexporter/writerV3.go
See https://github.com/SigNoz/signoz/pull/6616
Fixes https://github.com/SigNoz/signoz-otel-collector/issues/467
=> Stop wrting to v1 tag attributes table

pkg/metering/json.go, pkg/metering/meter.go, pkg/metering/v1/logs.go, pkg/metering/v1/logs_test.go, pkg/pdatagen/plogsgen/logs.go, pkg/pdatagen/plogsgen/options.go
- Add a pkg `metering` with interface `metering.Meter` for Size and Count usage calculation
- Add a pkg `pdatagen` for generating a wide variety of telemetry data for testing
=> feat(metering): add metering for logs

.github/workflows/ci.yaml, .github/workflows/postci.yaml
- use updated GitHub Label workflow
- fix CI condition to skip jobs for forks and dependabot, require label
=> ci(github): updated label workflow, fix ci skip condition

.github/workflows/ci.yaml
We will be deciding on whether to run the workflows based on the following conditions.
1. For `pull_request` events:
- The PR is from the same repository (not a fork) AND
- The actor is not dependabot AND
- The PR doesn't have the 'safe-to-test' label
2. For `pull_request_target` events:
- The PR has the 'safe-to-test' label
=> ci: update skip workflow conditions

.github/workflows/postci.yaml
- postci) use PR author instead of github.actor
=> ci(postci): use PR author instead of github.actor

pkg/metering/v1/metrics.go, pkg/metering/v1/metrics_test.go, pkg/pdatagen/pmetricsgen/data.go
Fixes https://github.com/SigNoz/engineering-pod/issues/2146
The `MetricCount` is not the count the user gets billed on if the data contains histograms. A sample is created from each bucket bound.
=> metering: Add metric metering

receiver/signozawsfirehosereceiver/internal/unmarshaler/cwlog/logsbuilder.go, receiver/signozawsfirehosereceiver/internal/unmarshaler/cwlog/unmarshaler_test.go
Cloudwatch log records contain timestamps in milliseconds.
OTLP log model expects timestamp to be in nanoseconds.
The forked code (from awsfirehose) was setting plog timestamp from the millisecond value leading to incorrect timestamps in parsed log records.
This change fixes that by correctly parsing the timestamp
contributes to https://github.com/SigNoz/signoz/issues/6540
=> Chore: signozawsfirehosereceiver cwlog ts unmarshaling

config/configrouter/mux.go, config/configrouter/mux_test.go, config/configrouter/writer.go, config/configrouter/writer_test.go, go.mod, receiver/signozawsfirehosereceiver/receiver.go
- Add the prefix `/firehouse/<record-type>` in the http handler
- Add panic handler and default route handling
=> fixes(signozfirehosereceiver): add prefixes to routes

exporter/clickhousemetricsexporter/exporter.go
For summary metrics, we were incorrectly setting the temporality as Unspecified. This was because there is no temporality field on the Summary point. It was clarified with this change https://github.com/open-telemetry/opentelemetry-proto/pull/591 that Summary metrics will always represent cumulative values. This change fixes it.
=> chore: summary metrics are always cumulative temporality

cmd/signozschemamigrator/schema_migrator/column.go, cmd/signozschemamigrator/schema_migrator/column_operations.go, cmd/signozschemamigrator/schema_migrator/column_operations_test.go, cmd/signozschemamigrator/schema_migrator/logs_migrations.go, cmd/signozschemamigrator/schema_migrator/table_operations.go, cmd/signozschemamigrator/schema_migrator/table_operations_test.go
Fixes https://github.com/SigNoz/engineering-pod/issues/2135
* adds ttl to the keys table of attributes and resource.
* also materializes the column to add ts to the old rows.
Wrote the TruncateTableOperation, it's not used but still kept it in the code.
=> fix: add ttl for keys table

exporter/clickhouselogsexporter/exporter.go
use logs table instead of distributed
issue was not noticed much becuase the value was set to current time during the start of the collector.
=> fix: use logs table instead of distributed

cmd/signozschemamigrator/schema_migrator/manager.go, cmd/signozschemamigrator/schema_migrator/metrics_migrations.go
We have added New Migration to remove unused MV's.
We have added IsNecessary properties to bypass migration checks.
Testing - 
We have run the migration in local , no more double mv's.
For sanity we have pushed one metric and checked it in all aggregated tables.
=> fix(7303): removed unused double mv's

exporter/signozclickhousemetrics/batch.go, exporter/signozclickhousemetrics/exporter.go, exporter/signozclickhousemetrics/exporter_test.go
1. metric name and temporality have interchanged values in metadata table
2. the name suffix we add for time series records is missing for the metadata
3. type of the `.sum`, `.count`, `.min`, `.max` are taking the type of metric, which is incorrect
=> fix: correct type and name for metadata records

pkg/metering/v1/metrics.go, pkg/metering/v1/metrics_test.go
- the metrics count package wasn't taking into account the sum / count / min / max metric datapoints that we generate for histogram, summary and exponential histogram metric types 
contributes to - https://github.com/SigNoz/platform-pod/issues/858
=> fix(metering): added missing metric metering

cmd/signozschemamigrator/schema_migrator/table_operations.go, cmd/signozschemamigrator/schema_migrator/table_operations_test.go, cmd/signozschemamigrator/schema_migrator/traces_migrations.go
This pull request adds a new migration to enhance the `span_attributes_keys` and `distributed_span_attributes_keys` tables in the traces database. The main goal is to introduce a `timestamp` column to both tables and set a time-to-live (TTL) policy, ensuring data retention aligns with related span tables.
Partially fixes: https://github.com/SigNoz/signoz-otel-collector/issues/663
Schema migration changes:
* Added a `timestamp` column with a default value to the `span_attributes_keys` table in the `signoz_traces` database.
* Set a TTL policy on the `span_attributes_keys` table to automatically expire records after 15 days using the new `timestamp` column.
* Added a `timestamp` column with a default value to the `distributed_span_attributes_keys` table in the `signoz_traces` database.
* Set …
=> Add TTL to `span_attributes_keys` table

exporter/signozclickhousemetrics/exporter.go
Moving NaN logs to debug. Its very noisy.
=> chore(signozclickhousemetrics): move warn to debug

cmd/signozschemamigrator/schema_migrator/manager.go
When clickhouse DDLWorker deletes the task before we query the distributed_ddl_queue, a error is thrown saying "No Node: Code: 999. Coordination::Exception: Coordination error: No node, path \/clickhouse\/signoz-clickhouse\/task_queue\/ddl\/query-0000001757."
We are adding a retry loop to prevent crashes of schema migrator when this happens
=> feat(manager): add a retry loop for no node coordination error
