SigNoz/signoz-otel-collector

Makefile
cmd/signozcollector/Dockerfile
cmd/signozcollector/components.go
exporter/clickhouselogsexporter/README.md
exporter/clickhouselogsexporter/config.go
exporter/clickhouselogsexporter/config_test.go
exporter/clickhouselogsexporter/example/README.md
exporter/clickhouselogsexporter/example/docker-compose.yml
exporter/clickhouselogsexporter/example/otel-collector-config.yml
exporter/clickhouselogsexporter/exporter.go
exporter/clickhouselogsexporter/factory.go
exporter/clickhouselogsexporter/factory_test.go
exporter/clickhouselogsexporter/migrations/000001_init_db.down.sql
exporter/clickhouselogsexporter/migrations/000001_init_db.up.sql
exporter/clickhouselogsexporter/testdata/config.yaml
go.mod
go.sum

FIXES https://github.com/SigNoz/signoz/issues/1141
FIXES [#534](https://github.com/SigNoz/engineering-pod/issues/534)

add clickhouselogsexporter

---

exporter/clickhousemetricsexporter/clickhouse.go

Fixes https://github.com/sigNoz/engineering-pod/issues/727

fix: override repeated label keys

---

cmd/signozcollector/components.go
exporter/clickhouselogsexporter/exporter.go
exporter/clickhouselogsexporter/factory.go

Fixes https://github.com/SigNoz/engineering-pod/issues/816

feat: clickhouselogsexporter updated to support v0.63

---

exporter/clickhouselogsexporter/config.go
exporter/clickhouselogsexporter/exporter.go
exporter/clickhousetracesexporter/clickhouse_exporter.go
exporter/clickhousetracesexporter/clickhouse_factory.go
exporter/clickhousetracesexporter/config.go
exporter/clickhousetracesexporter/options.go

Docker config PR: https://github.com/SigNoz/signoz/pull/1839

fix: add docker multi node cluster flag

---

cmd/signozcollector/main.go
components/components.go

Part of https://github.com/SigNoz/signoz/issues/1786

Move components to package

---

processor/signozspanmetricsprocessor/factory.go
processor/signozspanmetricsprocessor/processor.go
processor/signozspanmetricsprocessor/processor_test.go

Part of https://github.com/SigNoz/signoz/issues/2000

Add signoz.collector.id to span metrics processor

---

exporter/clickhouselogsexporter/exporter.go

Flush logs before exit

---

exporter/clickhouselogsexporter/exporter.go

Fixes https://github.com/SigNoz/signoz/issues/1806

Add default timestamp if timestamp is empty

---

exporter/clickhousetracesexporter/clickhouse_factory.go
exporter/clickhousetracesexporter/writer.go

closes: https://github.com/SigNoz/signoz-otel-collector/issues/77

chore: add trace exporter db latency

---

exporter/clickhouselogsexporter/exporter.go

Fixes https://github.com/SigNoz/signoz/issues/2047
also added default observed timestamp, for receivers live filelog the observedtimestamp is set but Kafka doesn't sent default observedtimestamp.

Add support for bytes body type

---

exporter/clickhouselogsexporter/migrations/000001_init_db.up.sql
exporter/clickhousemetricsexporter/clickhouse.go
exporter/clickhousetracesexporter/migrations/000007_init_signoz_index_v2.up.sql
exporter/clickhousetracesexporter/migrations/000008_init_signoz_spans.up.sql
exporter/clickhousetracesexporter/migrations/000011_init_durationMV.up.sql
exporter/clickhousetracesexporter/migrations/000012_init_signoz_error_index_v2.up.sql
exporter/clickhousetracesexporter/migrations/000014_add_usage_explorer_mv.up.sql
exporter/clickhousetracesexporter/migrations/000016_dependency_graph_minutes.up.sql

30days for metrics, 7 days for traces and logs

feat: set default TTL

---

exporter/clickhouselogsexporter/migrations/000005_attribute_rename.down.sql
exporter/clickhouselogsexporter/migrations/000005_attribute_rename.up.sql

fix: attribute name corrected in logs database

---

exporter/clickhouselogsexporter/migrations/000005_attribute_rename.down.sql
exporter/clickhouselogsexporter/migrations/000005_attribute_rename.up.sql

On cluster command was missed in the migration file, this fix adds the on cluster command https://github.com/SigNoz/signoz-otel-collector/issues/94

fix: on cluster command added to migration

---

exporter/clickhousetracesexporter/clickhouse_exporter.go
exporter/clickhousetracesexporter/migrations/000020_resource_att_exceptions.down.sql
exporter/clickhousetracesexporter/migrations/000020_resource_att_exceptions.up.sql
exporter/clickhousetracesexporter/schema-signoz.go
exporter/clickhousetracesexporter/writer.go

closes: https://github.com/SigNoz/signoz-otel-collector/issues/119

feat: add resource attributes to exception table

---

exporter/clickhouselogsexporter/exporter.go
exporter/clickhouselogsexporter/migrations/000006_tag_attributes.down.sql
exporter/clickhouselogsexporter/migrations/000006_tag_attributes.up.sql

Fixes https://github.com/SigNoz/signoz/issues/2254

feat: push tag attributes to a new table

---

exporter/clickhousetracesexporter/clickhouse_exporter.go
exporter/clickhousetracesexporter/clickhouse_factory.go
exporter/clickhousetracesexporter/migrations/000023_span_attributes_mv.up.sql
exporter/clickhousetracesexporter/migrations/000024_span_attributes_keys.down.sql
exporter/clickhousetracesexporter/migrations/000024_span_attributes_keys.up.sql
exporter/clickhousetracesexporter/options.go
exporter/clickhousetracesexporter/writer.go

This table will be used for cases when user writes a custom key

introduce span attributes keys table

---

components/components.go
go.mod
go.sum

Added awscloudwatch to receivers

feat: aws cloudwatch receiver added

---

.github/workflows/release.yaml

ci(release): 👷 GH workflow for release

---

exporter/clickhousetracesexporter/clickhouse_exporter.go
exporter/clickhousetracesexporter/clickhouse_factory.go
exporter/clickhousetracesexporter/options.go
exporter/clickhousetracesexporter/writer.go

fix: https://github.com/SigNoz/engineering-pod/issues/800

chore: remove trace batcher

---

.github/workflows/push.yaml
.github/workflows/release.yaml

ci(gh-workflows): 👷 push/release actions for schema-migrator

---

exporter/clickhouselogsexporter/exporter.go
exporter/clickhousetracesexporter/clickhouse_exporter.go
exporter/clickhousetracesexporter/clickhouse_factory.go
exporter/clickhousetracesexporter/options.go

to avoid `prepareBatch:clickhouse: acquire conn timeout`

fix: set maxOpenIdleConnections = numConsumers + 1

---

receiver/httplogreceiver/bodyparser/json.go
receiver/httplogreceiver/bodyparser/json_test.go
receiver/httplogreceiver/httplogreceiver.go

Fixes https://github.com/SigNoz/signoz/issues/3959
* Convert time to nanoseconds.
* return vercel verify token

fix: update httplogreceiver to support vercel

---

exporter/clickhousetracesexporter/clickhouse_exporter.go

close: https://github.com/SigNoz/signoz-otel-collector/issues/61

chore: flush spans before exit

---

go.mod
go.sum

Added a nil pointer check in the library for fixing this issue.
Also created a PR in the upstream repo https://github.com/ClickHouse/clickhouse-go/issues/1167

fix: replace ch library with fork

---

exporter/clickhousemetricsexporter/config_test.go
exporter/clickhousemetricsexporter/factory.go

See https://github.com/SigNoz/engineering-pod/issues/1059#issuecomment-1874839009

Enable WriteTSToV4 for everyone by default

---

signozcol/collector.go

feat: support env config provider

---

migrationmanager/migrators/logs/migrations/000009_add_usage.down.sql
migrationmanager/migrators/logs/migrations/000009_add_usage.up.sql
migrationmanager/migrators/metrics/migrations/000004_add_usage.down.sql
migrationmanager/migrators/metrics/migrations/000004_add_usage.up.sql
migrationmanager/migrators/traces/migrations/000026_add_usage.down.sql
migrationmanager/migrators/traces/migrations/000026_add_usage.up.sql
usage/usage.go

Fixes https://github.com/SigNoz/signoz-otel-collector/issues/268

fix: usage migration moved out of code to migrations

---

cmd/signozschemamigrator/migrate.go

chore: set SIGNOZ_REPLICATED env as empty string when not enabled

---

exporter/clickhousemetricsexporter/clickhouse.go
go.mod
go.sum

Reverts SigNoz/signoz-otel-collector#331
It occurred to me how this fails under a particular case. Reverting for now.

Revert "Skip write to time_series_v4 table for the same fingerprint in curren…"

---

exporter/clickhousemetricsexporter/clickhouse.go

This change moves the counting samples for usage from `samples_v2` to `samples_v4`. There is no logical change. Just the code is moved to the new block.

Move usage to new table write block

---

exporter/clickhousetracesexporter/clickhouse_exporter.go

Close https://github.com/SigNoz/signoz-otel-collector/issues/368

chore: update db attribute names

---

exporter/clickhouselogsexporter/exporter.go

write to old table only if use_new_schema=false
fixes https://github.com/SigNoz/signoz-otel-collector/issues/375

feat: write to old table only if use_new_schema=false

---

exporter/clickhousemetricsexporter/clickhouse.go
exporter/clickhousemetricsexporter/config.go
exporter/clickhousemetricsexporter/config_test.go
exporter/clickhousemetricsexporter/exporter.go
exporter/clickhousemetricsexporter/factory.go

By default not disabled. This is not needed for any new customers.

Add support for disabling v2

---

cmd/signozschemamigrator/schema_migrator/column.go

This PR adds a `Column` that is used to describe the CH column in code. This will be used to implement all the operations on column.

Add column definition

---

.github/workflows/ci.yaml

- Add the pull_request_target for runnings ci checks on forks
- A label called `runci` will need to be put to run ci checks

fix(primus): add pull_request_target

---

receiver/clickhousesystemtablesreceiver/query_log.go
receiver/clickhousesystemtablesreceiver/query_log_test.go
receiver/clickhousesystemtablesreceiver/receiver_test.go

Fixes https://github.com/SigNoz/signoz-otel-collector/issues/441

Data usability improvements for query_log

---

cmd/signozschemamigrator/schema_migrator/column.go
cmd/signozschemamigrator/schema_migrator/column_operations_test.go
cmd/signozschemamigrator/schema_migrator/table_operations_test.go

support for alias in schema migrator

fix: support for alias in schema migrator

---

cmd/signozschemamigrator/schema_migrator/projection_operations.go
cmd/signozschemamigrator/schema_migrator/projection_operations_test.go

Add projection operations.
FOR https://github.com/SigNoz/signoz/issues/5713

feat: add projection operations

---

exporter/clickhouselogsexporter/exporter.go

logs part of https://github.com/SigNoz/signoz-otel-collector/issues/472

Add write cache for logs_v2_resource

---

cmd/signozschemamigrator/schema_migrator/logs_migrations.go
exporter/clickhouselogsexporter/config.go
exporter/clickhouselogsexporter/config_test.go
exporter/clickhouselogsexporter/exporter.go
exporter/clickhouselogsexporter/factory.go
utils/utils.go

Logs part of https://github.com/SigNoz/signoz-otel-collector/issues/467

Add logs tag attributes v2 with max distinct values limit

---

exporter/metadataexporter/vt.go
exporter/metadataexporter/vt_test.go

Part 2 of breakdown https://github.com/SigNoz/signoz-otel-collector/pull/479

Add unique value tracker

---

exporter/metadataexporter/exporter.go

Part 3 of breakdown https://github.com/SigNoz/signoz-otel-collector/pull/479
- periodically fetch the count from DB to decided if a key should be skipped
- maintain a local tracker to skip a key
- if it passes both stages, then check in fingerprint cache to see if it has been inserted already
- if not, then insert

Implement PushTraces

---

exporter/metadataexporter/exporter.go

Part 4 of breakdown https://github.com/SigNoz/signoz-otel-collector/pull/479

Implement PushLogs

---

exporter/metadataexporter/exporter.go

Part 5 of breakdown https://github.com/SigNoz/signoz-otel-collector/pull/479

Implement PushMetrics

---

exporter/clickhousemetricsexporterv2/exporter.go
exporter/clickhousemetricsexporterv2/factory.go

Fixes https://github.com/SigNoz/signoz-otel-collector/issues/491

fix: nil meter instance used in exporter

---

exporter/clickhouselogsexporter/exporter.go

Add missing exporter ID

---

.github/workflows/ci.yaml

ci: skip workflow run from fork

---

.github/workflows/ci.yaml

ci(github): update ci workflow

---

.github/workflows/postci.yaml

ci(github): update postci workflow

---

.github/workflows/ci.yaml

ci: update skip condition

---

.github/workflows/ci.yaml

- use PR author instead of `github.actor`

ci: use PR author instead of github.actor

---

cmd/signozschemamigrator/schema_migrator/analytics_migrations.go
cmd/signozschemamigrator/schema_migrator/manager.go
cmd/signozschemamigrator/schema_migrator/schema_migrations_v2_tables.go

Fixes https://github.com/SigNoz/platform-pod/issues/402

fix: move analytics schema migrations

---

.gitignore
exporter/clickhousemetricsexporterv2/exporter.go

feat(exporter): send writes in parallel

---

exporter/metadataexporter/exporter.go

The logs have become too noisy. Moved relevant logs to debug.

feat(metadata): move to debug logs

---

exporter/clickhousemetricsexporter/clickhouse.go
exporter/signozclickhousemetrics/exporter.go
exporter/signozclickhousemetrics/factory.go

Added correct exporter attribute for duration histogram

fix(signozclickhousemetrics): added correct exporter attributes 

---

exporter/clickhouselogsexporter/usage.go
exporter/clickhousetracesexporter/schema-signoz.go

contributes to - https://github.com/SigNoz/platform-pod/issues/858

fix(meter): difference between exporter usage metrics and metering sizers

---

exporter/clickhouselogsexporter/exporter.go

The last pr we have added more columns to resource table but the insert statement didn't have the column names and since cache was used the issue was not visible during review. As the insert queries are not fired everytime.

fix: use insert sql for resource table
